name: Bug Report
description: Report a problem or unexpected behavior
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - hstefanov1
type: bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal set of steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How do you classify the severity of this issue?
      options:
        - Critical (system crash / data loss)
        - High (major feature broken)
        - Medium (unexpected behavior)
        - Low (cosmetic issue)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: What OS are you using?
      placeholder: e.g., macOS 14, Ubuntu 22.04, Windows 11
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g., 1.0.1
    validations:
      required: true

  - type: input
    id: runtime
    attributes:
      label: Runtime
      description: What is your runtime?
      placeholder: e.g., Node 20, Java 21
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or stack traces
      description: |
        Paste logs or stack traces here.
        They will be automatically formatted.
        Please remove sensitive data.
      render: shell

  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots / files
      description: Paste screenshots or drag & drop files here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the project [Code of Conduct](https://github.com/stefshield/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
